server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skillshare
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 153839165944-2qg53k1pf9pnadrmk8qosdpoddlg4bka.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile
            redirect-uri: http://localhost:8081/login/oauth2/code/google
            authorization-grant-type: authorization_code
          facebook:
            client-id: your_facebook_client_id
            client-secret: your_facebook_client_secret
            scope: email,public_profile
            redirect-uri: http://localhost:8081/login/oauth2/code/facebook
            authorization-grant-type: authorization_code
        provider:
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
# AWS S3 Configuration
aws:
  accessKeyId: AKIA6A7SNCU2WYIEM7JK
  secretAccessKey: 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
  region: eu-north-1
  s3:
    bucket: skillsharebucket